[pytest]
markers =
    alignment: minimal cost demo tests for alignment module
    index: faiss index
    library: entire library
    llm_cloud: cloud llms test
    openai: openai
    anthropic: anthropic
filterwarnings =
    ignore:builtin type SwigPyPacked has no __module__:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__:DeprecationWarning
